/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'TOBIIEEE' at '11/29/16 10:33 AM' with Gradle 2.14.1
 *
 * @author TOBIIEEE, @date 11/29/16 10:33 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
